name = "BaryRational"
uuid = "91aaffc3-5777-4842-85b7-5d3d5d6a3494"
authors = ["Don MacMillen <don@macmillen.net> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"


[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
julia = "1.5"

[targets]
test = ["Random", "SpecialFunctions", "Test", "ForwardDiff"]
